[package]
name = "trader"
version = "0.1.0"
authors = ["Petr Brazdil <p.brazdil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oms = { path = "../oms" }
feed = { path = "../feed" }
